/* You can add config revalidate into file /api/revalidate/route.ts */
export const REVALIDATE_KEYS = {
  articles: 'articles',
  global: 'global',
  teammember: 'teammember',
  jobs: 'jobs',
  'club-and-activity': 'club-and-activity',
  advisory: 'advisory',
  'experiential-education': 'experiential-education',
  banners: 'banners',
  admission: 'admission',
  'student-well-being': 'student-well-being',
  'cpoms-page': 'cpoms-page',
  'leadership-opportunities': 'leadership-opportunities',
  library: 'library',
  policy: 'policy',
  'the-deltas-page': 'the-deltas-page',
  'mission-and-vision': 'mission-and-vision',
  'dgs-history': 'dgs-history',
  'academics-middle-school': 'academics-middle-school',
  'academics-high-school': 'academics-high-school',
  'academics-college-counseling': 'academics-college-counseling',
  'about-our-team': 'about-our-team',
};

export enum STRAPI_MODEL {
  Articles = 'article',
  Global = 'global',
  Teammember = 'teammember',
  ClubAndActivity = 'club-and-activity',
  Job = 'job',
  Advisory = 'advisory',
  ExperientialEducation = 'experiential-education',
  Banner = 'banner',
  Admission = 'admission',
  StudentWellBeing = 'student-well-being',
  CpomsPage = 'cpoms-page',
  LeadershipOpportunities = 'leadership-opportunities',
  Library = 'library',
  Policy = 'policy',
  TheDeltasPage = 'the-deltas-page',
  MissionAndVision = 'mission-and-vision',
  DgsHistory = 'dgs-history',
  AcademicsMiddleSchool = 'academics-middle-school',
  AcademicsHighSchool = 'academics-high-school',
  AcademicsCollegeCounseling = 'academics-college-counseling',
  AboutOurTeam = 'about-our-team',
}
