/* You can add config revalidate into file /api/revalidate/route.ts */
export const REVALIDATE_KEYS = {
  articles: 'articles',
  global: 'global',
  teammember: 'teammember',
  'academics-story': 'academics-story',
  jobs: 'jobs',
  'club-and-activity': 'club-and-activity',
  advisory: 'advisory',
  'experiential-education': 'experiential-education',
  banners: 'banners',
  admission: 'admission',
  'student-well-being': 'student-well-being',
  'cpoms-page': 'cpoms-page',
  'leadership-opportunities': 'leadership-opportunities',
  library: 'library',
  policy: 'policy',
};

export enum STRAPI_MODEL {
  Articles = 'article',
  Global = 'global',
  Teammember = 'teammember',
  AcademicsStory = 'academics-story',
  ClubAndActivity = 'club-and-activity',
  Job = 'job',
  Advisory = 'advisory',
  ExperientialEducation = 'experiential-education',
  Banner = 'banner',
  Admission = 'admission',
  StudentWellBeing = 'student-well-being',
  CpomsPage = 'cpoms-page',
  LeadershipOpportunities = 'leadership-opportunities',
  Library = 'library',
  Policy = 'policy',
}
